version: '3.8'

services:
  backend:
    build: 
      context: './backend'
      dockerfile: Dockerfile
    container_name: scheduling_backend
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./backend:/app-backend
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  mysql_data:
